### PR TITLE
add archeoViz-related material

### PR DESCRIPTION
**Pull request by sebastien-plutniak**
I'm submitting a series of tutorial and class syllabus using the archeoViz application to introduce various concepts regarding digital archaeology.

### CODE REVIEW

**Comment by nevrome** [comment]
Cool! I fear, though, that your editor replaced all tabs with one or multiple spaces. And I think our parser may only work with tabs. Could you please adjust this?

**Comment by sebastien-plutniak** [comment]
Ups, thanks, I've corrected the separator!

**Comment by nevrome** [comment]
OK - this issue should be fixed on the main branch now. Could you please merge this main branch again into your fork (I think GitHub calls this to "sync") to finally enable proper validation? Sorry for the hassle.

**Comment by nevrome** [comment]
Great - thanks! We have a properly failing validation run now:

```
Running 1 tests. To reproduce these results later,
run elm-test-rs with --seed 3475926421 and --fuzz 100
↓ Pseudo-test for teaching material list validation
✗ if the .tsv table can be parsed
    Err "I saw 2 problems while decoding this CSV:\n\nThere was a problem on row 48, in the `Citation` field (column 17): I couldn't find the `Citation` column.\n\nThere was a problem on row 49, in the `Citation` field (column 17): I couldn't find the `Citation` column."
    ╷
    │ Expect.ok
    ╵
    Ok _
TEST RUN FAILED
Duration: 21 ms
Passed:   0
Failed:   1
```

I think this may be caused by some wrong delimiter. I'll merge now to investigate and fix this.

**Comment by nevrome** [comment]
It was the trailing empty lines at the end of the document.

**Comment by sebastien-plutniak** [comment]
Here we are! Thanks and sorry for the inconvenience!

**Pull request merged**
